package br.com.ronick.view;

import br.com.ronick.view.produto.EntradaNoEstoqueGUI;
import br.com.ronick.view.produto.RemoverProdutoGUI;
import br.com.ronick.view.produto.CadastrarProdutoGUI;
import br.com.ronick.view.produto.AlterarProdutoGUI;
import br.com.ronick.view.cliente.RemoverClienteGUI;
import br.com.ronick.view.cliente.CadastrarClienteGUI;
import br.com.ronick.view.cliente.AlterarClienteGUI;
import br.com.ronick.controller.BaseFacade;
import br.com.ronick.model.DAO.VendaDAO;
import br.com.ronick.view.usuario.AlterarUsuarioGUI;
import br.com.ronick.view.usuario.CadastrarUsuarioGUI;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 * @author ronick
 */
public class TelaPrincipalGUI extends javax.swing.JFrame {

    // Instanciação de objetos e declaração de variáveis

    public TelaPrincipalGUI() {

        initComponents();
        telaUsuario();
        atualiza();
    }

    public void telaUsuario() {
        InicioGUI tInicio = new InicioGUI(this, true);
        tInicio.setVisible(true);
        BaseFacade.fecharPrograma(tInicio.entrarPrincipal);
        lNomeUsuario.setText("Bem Vindo " + tInicio.nomeUsuario);
    }

    public void atualiza() {
        String[] cposCliente = {"Nome", "CPF", "Telefone", "Endereço"};
        String[][] dadosCliente;
        dadosCliente = BaseFacade.dadosDosClientes(cposCliente);
        DefaultTableModel modelo = new DefaultTableModel(
                dadosCliente, cposCliente);
        tClieCadastrados.setModel(modelo);
        
        String[] cposProduto = {"Nome", "Preço", "Qtde de Estoque", "Codigo do Produto"};
        String[][] dadosProduto;
        dadosProduto = BaseFacade.dadosDosProdutos(cposProduto);
        DefaultTableModel modelo2 = new DefaultTableModel(
                dadosProduto, cposProduto);
        tProdCadastrados.setModel(modelo2);
        
        String[] cposVenda = {"ID Venda", "CPF do Comprador", "Codigo do Produto", "Valor da Venda"};
        String[][] dadosVenda;
        dadosVenda = BaseFacade.dadosDasVendas(cposProduto);
        DefaultTableModel modelo3 = new DefaultTableModel(
                dadosVenda, cposVenda);
        tVenda.setModel(modelo3);
        
        int total = VendaDAO.totalValor();
        txValorTotal.setText(String.format(""+total));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pPrincipal = new javax.swing.JPanel();
        lNomeUsuario = new javax.swing.JLabel();
        tech = new javax.swing.JLabel();
        buy = new javax.swing.JLabel();
        lojaDeEletronico = new javax.swing.JLabel();
        bRealizarVenda = new javax.swing.JButton();
        labelValorCaixa = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txValorTotal = new javax.swing.JTextPane();
        TabelaClienteProduto = new javax.swing.JTabbedPane();
        tClientesCadastrados = new javax.swing.JScrollPane();
        tClieCadastrados = new javax.swing.JTable();
        tProdutosCadastrados = new javax.swing.JScrollPane();
        tProdCadastrados = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tVenda = new javax.swing.JTable();
        ImageIcon icon = new ImageIcon(getClass().getResource("/image/fundo2.jpg"));
        Image image = icon.getImage();
        jDPane = new javax.swing.JDesktopPane() {
            public void paintComponent(Graphics g) {
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        bAtualizar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mbNovoUsuario = new javax.swing.JMenuItem();
        mbAlteraUsuario = new javax.swing.JMenuItem();
        mCliente = new javax.swing.JMenu();
        mbCadastrarCliente = new javax.swing.JMenuItem();
        mbAlterarCliente = new javax.swing.JMenuItem();
        mbRemoverCliente = new javax.swing.JMenuItem();
        mProduto = new javax.swing.JMenu();
        mbCadastrarProduto = new javax.swing.JMenuItem();
        mbAlterarProduto = new javax.swing.JMenuItem();
        mbRemoverProduto = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Techbuy Loja de Eletrônico - Homepage");

        pPrincipal.setBackground(new java.awt.Color(0, 70, 74));

        lNomeUsuario.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        lNomeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lNomeUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lNomeUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        tech.setBackground(new java.awt.Color(255, 255, 255));
        tech.setFont(new java.awt.Font("Microsoft Himalaya", 0, 100)); // NOI18N
        tech.setForeground(new java.awt.Color(255, 255, 255));
        tech.setText("Tech");
        tech.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        buy.setBackground(new java.awt.Color(0, 0, 0));
        buy.setFont(new java.awt.Font("Microsoft Himalaya", 0, 100)); // NOI18N
        buy.setForeground(new java.awt.Color(255, 255, 51));
        buy.setText("Buy");
        buy.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lojaDeEletronico.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lojaDeEletronico.setForeground(new java.awt.Color(255, 255, 255));
        lojaDeEletronico.setText("Loja de Eletrônicos");
        lojaDeEletronico.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        bRealizarVenda.setBackground(new java.awt.Color(0, 102, 0));
        bRealizarVenda.setFont(new java.awt.Font("Microsoft Himalaya", 0, 24)); // NOI18N
        bRealizarVenda.setForeground(new java.awt.Color(255, 255, 255));
        bRealizarVenda.setText("Realizar Nova Venda");
        bRealizarVenda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bRealizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRealizarVendaActionPerformed(evt);
            }
        });

        labelValorCaixa.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        labelValorCaixa.setForeground(new java.awt.Color(255, 255, 255));
        labelValorCaixa.setText("Valor no caixa");

        txValorTotal.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jScrollPane3.setViewportView(txValorTotal);

        TabelaClienteProduto.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        TabelaClienteProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tClieCadastrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Telefone", "Endereço"
            }
        ));
        tClientesCadastrados.setViewportView(tClieCadastrados);

        TabelaClienteProduto.addTab("Clientes Cadastrados", tClientesCadastrados);

        tProdCadastrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo do Produto", "Produto", "Preço", "Quantidade em Estoque"
            }
        ));
        tProdutosCadastrados.setViewportView(tProdCadastrados);

        TabelaClienteProduto.addTab("Produtos Cadastrados", tProdutosCadastrados);

        tVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo da Venda", "CPF do Comprador", "Valor da Compra"
            }
        ));
        jScrollPane1.setViewportView(tVenda);

        TabelaClienteProduto.addTab("Histórico de Vendas", jScrollPane1);

        javax.swing.GroupLayout jDPaneLayout = new javax.swing.GroupLayout(jDPane);
        jDPane.setLayout(jDPaneLayout);
        jDPaneLayout.setHorizontalGroup(
            jDPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDPaneLayout.setVerticalGroup(
            jDPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        bAtualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bAtualizar.setText("Atualizar");
        bAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pPrincipalLayout = new javax.swing.GroupLayout(pPrincipal);
        pPrincipal.setLayout(pPrincipalLayout);
        pPrincipalLayout.setHorizontalGroup(
            pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPrincipalLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pPrincipalLayout.createSequentialGroup()
                        .addComponent(jDPane)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TabelaClienteProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pPrincipalLayout.createSequentialGroup()
                        .addComponent(labelValorCaixa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pPrincipalLayout.createSequentialGroup()
                        .addGroup(pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bRealizarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 468, Short.MAX_VALUE)
                        .addGroup(pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lojaDeEletronico, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPrincipalLayout.createSequentialGroup()
                                .addComponent(tech)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buy)))))
                .addGap(34, 34, 34))
        );
        pPrincipalLayout.setVerticalGroup(
            pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPrincipalLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPrincipalLayout.createSequentialGroup()
                        .addComponent(lojaDeEletronico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tech)
                            .addComponent(buy)))
                    .addGroup(pPrincipalLayout.createSequentialGroup()
                        .addComponent(lNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(bRealizarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TabelaClienteProduto)
                    .addComponent(jDPane))
                .addGap(18, 18, 18)
                .addGroup(pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelValorCaixa)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 51, 51));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMenuBar1.setForeground(new java.awt.Color(0, 51, 51));

        jMenu1.setText("Usuario");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        mbNovoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mbNovoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N
        mbNovoUsuario.setText("Novo usuario");
        mbNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbNovoUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(mbNovoUsuario);

        mbAlteraUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mbAlteraUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user_edit.png"))); // NOI18N
        mbAlteraUsuario.setText("Alterar senha de usuario");
        mbAlteraUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbAlteraUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(mbAlteraUsuario);

        jMenuBar1.add(jMenu1);

        mCliente.setText("Cliente");
        mCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        mbCadastrarCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mbCadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/group_add.png"))); // NOI18N
        mbCadastrarCliente.setText("Cadastrar novo cliente");
        mbCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbCadastrarClienteActionPerformed(evt);
            }
        });
        mCliente.add(mbCadastrarCliente);

        mbAlterarCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mbAlterarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/group_edit.png"))); // NOI18N
        mbAlterarCliente.setText("Alterar cadastro do cliente");
        mbAlterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbAlterarClienteActionPerformed(evt);
            }
        });
        mCliente.add(mbAlterarCliente);

        mbRemoverCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mbRemoverCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user_delete.png"))); // NOI18N
        mbRemoverCliente.setText("Remover cliente");
        mbRemoverCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbRemoverClienteActionPerformed(evt);
            }
        });
        mCliente.add(mbRemoverCliente);

        jMenuBar1.add(mCliente);

        mProduto.setText("Produto");
        mProduto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        mbCadastrarProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mbCadastrarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/package_add.png"))); // NOI18N
        mbCadastrarProduto.setText("Cadastrar novo produto");
        mbCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbCadastrarProdutoActionPerformed(evt);
            }
        });
        mProduto.add(mbCadastrarProduto);

        mbAlterarProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mbAlterarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/package_link.png"))); // NOI18N
        mbAlterarProduto.setText("Alterar produto");
        mbAlterarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbAlterarProdutoActionPerformed(evt);
            }
        });
        mProduto.add(mbAlterarProduto);

        mbRemoverProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mbRemoverProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/package_delete.png"))); // NOI18N
        mbRemoverProduto.setText("Remover produto");
        mbRemoverProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbRemoverProdutoActionPerformed(evt);
            }
        });
        mProduto.add(mbRemoverProduto);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/package_go.png"))); // NOI18N
        jMenuItem1.setText("Entrada no estoque");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mProduto.add(jMenuItem1);

        jMenuBar1.add(mProduto);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mbCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbCadastrarClienteActionPerformed
        CadastrarClienteGUI tCadCliente = new CadastrarClienteGUI();
        jDPane.add(tCadCliente);
        tCadCliente.setVisible(true);
    }//GEN-LAST:event_mbCadastrarClienteActionPerformed

    private void mbAlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbAlterarClienteActionPerformed
        AlterarClienteGUI tAltCliente = new AlterarClienteGUI();
        jDPane.add(tAltCliente);
        tAltCliente.setVisible(true);
    }//GEN-LAST:event_mbAlterarClienteActionPerformed

    private void mbRemoverClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbRemoverClienteActionPerformed
        RemoverClienteGUI tRemCliente = new RemoverClienteGUI();
        jDPane.add(tRemCliente);
        tRemCliente.setVisible(true);
    }//GEN-LAST:event_mbRemoverClienteActionPerformed

    private void mbCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbCadastrarProdutoActionPerformed
        CadastrarProdutoGUI tCadProduto = new CadastrarProdutoGUI();
        jDPane.add(tCadProduto);
        tCadProduto.setVisible(true);
    }//GEN-LAST:event_mbCadastrarProdutoActionPerformed

    private void mbAlterarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbAlterarProdutoActionPerformed
        AlterarProdutoGUI tAltProduto = new AlterarProdutoGUI();
        jDPane.add(tAltProduto);
        tAltProduto.setVisible(true);
    }//GEN-LAST:event_mbAlterarProdutoActionPerformed

    private void mbRemoverProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbRemoverProdutoActionPerformed
        RemoverProdutoGUI tRemProduto = new RemoverProdutoGUI();
        jDPane.add(tRemProduto);
        tRemProduto.setVisible(true);
    }//GEN-LAST:event_mbRemoverProdutoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        EntradaNoEstoqueGUI tEntEstoque = new EntradaNoEstoqueGUI();
        jDPane.add(tEntEstoque);
        tEntEstoque.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void bRealizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRealizarVendaActionPerformed
        RealizarVendaGUI tRealVenda = new RealizarVendaGUI();
        jDPane.add(tRealVenda);
        tRealVenda.setVisible(true);
    }//GEN-LAST:event_bRealizarVendaActionPerformed

    private void bAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtualizarActionPerformed
        atualiza();
    }//GEN-LAST:event_bAtualizarActionPerformed

    private void mbNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbNovoUsuarioActionPerformed
        CadastrarUsuarioGUI tCadUser = new CadastrarUsuarioGUI();
        jDPane.add(tCadUser);
        tCadUser.setVisible(true);
    }//GEN-LAST:event_mbNovoUsuarioActionPerformed

    private void mbAlteraUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbAlteraUsuarioActionPerformed
        AlterarUsuarioGUI tAltUser = new AlterarUsuarioGUI();
        jDPane.add(tAltUser);
        tAltUser.setVisible(true);
    }//GEN-LAST:event_mbAlteraUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalGUI().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabelaClienteProduto;
    private javax.swing.JButton bAtualizar;
    private javax.swing.JButton bRealizarVenda;
    private javax.swing.JLabel buy;
    private javax.swing.JDesktopPane jDPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lNomeUsuario;
    private javax.swing.JLabel labelValorCaixa;
    private javax.swing.JLabel lojaDeEletronico;
    private javax.swing.JMenu mCliente;
    private javax.swing.JMenu mProduto;
    private javax.swing.JMenuItem mbAlteraUsuario;
    private javax.swing.JMenuItem mbAlterarCliente;
    private javax.swing.JMenuItem mbAlterarProduto;
    private javax.swing.JMenuItem mbCadastrarCliente;
    private javax.swing.JMenuItem mbCadastrarProduto;
    private javax.swing.JMenuItem mbNovoUsuario;
    private javax.swing.JMenuItem mbRemoverCliente;
    private javax.swing.JMenuItem mbRemoverProduto;
    private javax.swing.JPanel pPrincipal;
    private javax.swing.JTable tClieCadastrados;
    private javax.swing.JScrollPane tClientesCadastrados;
    private javax.swing.JTable tProdCadastrados;
    private javax.swing.JScrollPane tProdutosCadastrados;
    private javax.swing.JTable tVenda;
    private javax.swing.JLabel tech;
    private javax.swing.JTextPane txValorTotal;
    // End of variables declaration//GEN-END:variables
}
